// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfiejpfajwyqxqacpwyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmaWVqcGZhand5cXhxYWNwd3l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyNTAwOTYsImV4cCI6MjA1MDgyNjA5Nn0.8yKuDC2zLTjJwi_uTxJ0W_y6C8kwHjujsp3r-47Zgg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);